base_string = "CCTGGCGAACGGACCACCGGATCGGTCTCCGAATAATCGGTAAACGCCGGTTTACACTCCGGACTAGCACCGAGCACCCTCGATTGCACAGTTTTCTTACTTGGTAAAGTTACTTACGAACAGCTGTCAGTGCGCAGCCTGTGGGGCTCACGGGGATGACGTGATCCTCTCTGCAAACGCTATTGCTTGTTATCGTGAATTTCTTTGGCCTCCTGAGTGGCTCCCTCTTCGCCATTGATCAGGTGTCGGTCACCCCCACTCCTGGGCGTCCCCCTGGCCCACTGGGACCAGGACCGTGGCCTTCCGCCCTATCAAAAGAGTCATTTGAATCAGATCTTTAGCGGCTGCCCGAACATAAGGACATTGAATGGAATGTACTCGCGCCGGGAGAAGACTGTCGGTATGCTTATGCGGGCAACACGGTGCGATGCCGGATCCTTCAAAGTTAGGAGCACGTCATAGTGGTCGGTATCTACTCGCCTCATTTATAATGCAGAAAGTGCTCCACAGGGAAAGCCCATCAGTGACGGGCTTTAGGTGTAGCGGCCAGGAGGTGATATCGTACTCGGGACTATTAGTAGTCTCAGTTAGTTTTGCACTTGACCAGTTCCTATGTGATTAGACGCCTAGTCTACAGGAAGCGAGCAGGCTTGGTTGCTTGGCTCCTTGCCCGAGAGTCACCTCGGCATTACAGGTTCTTCGATAATAGCGGGCGCAGCGCTTAGATAGCGTACTTACCCCACCTAGCGGGACACAGGCGCGCCTTGTTTACGCTATAGACATTGGCCGACGAAGTAGTGCGTACTGTTTAATGCCATACCTACGTGTTGCTTGG"

#Reverse Function
def reverse_it(x):
    x.reverse()

#Replacement Function
def replace_stuff(x):
    if (x == "T"):
        return "A"
    elif (x == "A"):
        return "T"
    elif (x == "G"):
        return "C"
    elif (x == "C"):
        return "G"
    else:
        return x

# Orchestrate Function
def transform_string(x):
    x_as_list = list(x)
    reversed_x = reversed(x_as_list)
    replaced_x = list(map(replace_stuff, reversed_x))
    return ''.join(replaced_x)

print(transform_string(base_string))
